- name: Fetch join script from master to controller
  fetch:
    src: /tmp/k8s_join_cmd.sh
    dest: /tmp/k8s_join_cmd.sh
    flat: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Copy join script to worker
  copy:
    src: /tmp/k8s_join_cmd.sh        # path on controller
    dest: /tmp/k8s_join_cmd.sh       # path on worker
    mode: '0755'

- name: Join node to cluster
  command: bash /tmp/k8s_join_cmd.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
